//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtisCode.Aplicacion.Model.db_Local
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtisAPIConfiguracionEntorno
    {
        public int AtisAPIConfiguracionEntornoID { get; set; }
        public string Protocolo { get; set; }
        public string URLServidor { get; set; }
        public int Puerto { get; set; }
        public string URLDirectorio { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string TipoAmbiente { get; set; }
        public bool Estado { get; set; }
        public int AtisAplicacionID { get; set; }
    
        public virtual AtisAplicacion AtisAplicacion { get; set; }
    }
}
