//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtisCode.Aplicacion.Model.db_Local
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtisSafiCredenciales
    {
        public int AtisSafiCredencialesID { get; set; }
        public string PostmanToken { get; set; }
        public string CacheControl { get; set; }
        public string ContentType { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int Anio { get; set; }
        public string GrantType { get; set; }
        public bool Estado { get; set; }
    }
}
