//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtisCode.Aplicacion.Model.db_Local
{
    using System;
    
    public partial class ConfiguracionPrincipalInfo
    {
        public int Id { get; set; }
        public int EstadoSwitchTransaccion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Segmento { get; set; }
        public string PtoEmi { get; set; }
        public Nullable<int> Ambiente { get; set; }
        public Nullable<int> Iva { get; set; }
        public string RazonSocial { get; set; }
        public string CodProducto { get; set; }
        public string NombProducto { get; set; }
        public string CategoriaCliente { get; set; }
        public string CuentaContable { get; set; }
        public Nullable<int> GrupoCredito { get; set; }
        public string TributaImpuesto { get; set; }
        public string DocumentoElectronico { get; set; }
        public string Relacionado { get; set; }
        public string VendedorSeccion { get; set; }
        public string ListaPrecioContado { get; set; }
        public string ListaPrecioCredito { get; set; }
        public Nullable<int> LimiteCredito { get; set; }
        public string Uge { get; set; }
        public string Bodega { get; set; }
        public string Tipo { get; set; }
        public string Status { get; set; }
        public string Contribuyente { get; set; }
        public string Ciudad { get; set; }
        public string Telefono { get; set; }
        public int AtisAplicacionID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool EstadoAplicacion { get; set; }
        public int IdEmpresa { get; set; }
        public string Establecimiento { get; set; }
        public string RUC { get; set; }
        public string DireccionMatriz { get; set; }
        public long IdSwitchTransacciones { get; set; }
        public int Estado { get; set; }
        public int EmpresaSwitchTransaccionesID { get; set; }
    }
}
