//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtisCode.Aplicacion.Model.db_Local
{
    using System;
    
    public partial class ElancesWebServicesAmbienteInfo
    {
        public int AtisAPIConfiguracionEntornoID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string URLServidor { get; set; }
        public string UrlAPI { get; set; }
        public string TipoAmbiente { get; set; }
        public bool EstadoConfiguracion { get; set; }
        public string NombreAplicacion { get; set; }
        public string DescripcionAplicacion { get; set; }
        public bool EstadoAplicacion { get; set; }
    }
}
