//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtisCode.Aplicacion.Model.db_Local
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.EmpresaSwitchTransacciones = new HashSet<EmpresaSwitchTransacciones>();
        }
    
        public int IdEmpresa { get; set; }
        public string Establecimiento { get; set; }
        public string RazonSocial { get; set; }
        public string RUC { get; set; }
        public string DireccionMatriz { get; set; }
        public bool TributaImpuesto { get; set; }
        public string Contribuyente { get; set; }
        public string Ciudad { get; set; }
        public string Telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaSwitchTransacciones> EmpresaSwitchTransacciones { get; set; }
    }
}
