//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtisCode.Aplicacion.Model.db_Local
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SwitchAtiscodeEntities : DbContext
    {
        public SwitchAtiscodeEntities()
            : base("name=SwitchAtiscodeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AtisAPIConfiguracionEntorno> AtisAPIConfiguracionEntorno { get; set; }
        public virtual DbSet<AtisAplicacion> AtisAplicacion { get; set; }
        public virtual DbSet<AtisSafiCredenciales> AtisSafiCredenciales { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<EmpresaSwitchTransacciones> EmpresaSwitchTransacciones { get; set; }
        public virtual DbSet<SwitchTransacciones> SwitchTransacciones { get; set; }
        public virtual DbSet<AtisLogTran> AtisLogTran { get; set; }
        public virtual DbSet<AtisQueueTransactions> AtisQueueTransactions { get; set; }
    
        public virtual ObjectResult<ConfiguracionPrincipalInfo> ConsultarConfiguracionPrincipal(string iNombre)
        {
            var iNombreParameter = iNombre != null ?
                new ObjectParameter("iNombre", iNombre) :
                new ObjectParameter("iNombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConfiguracionPrincipalInfo>("ConsultarConfiguracionPrincipal", iNombreParameter);
        }
    
        public virtual ObjectResult<ElancesWebServicesAmbienteInfo> ConsultarElancesWebServicesAmbiente(string iNombreAplicacion, string iTipoAmbiente)
        {
            var iNombreAplicacionParameter = iNombreAplicacion != null ?
                new ObjectParameter("iNombreAplicacion", iNombreAplicacion) :
                new ObjectParameter("iNombreAplicacion", typeof(string));
    
            var iTipoAmbienteParameter = iTipoAmbiente != null ?
                new ObjectParameter("iTipoAmbiente", iTipoAmbiente) :
                new ObjectParameter("iTipoAmbiente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ElancesWebServicesAmbienteInfo>("ConsultarElancesWebServicesAmbiente", iNombreAplicacionParameter, iTipoAmbienteParameter);
        }
    
        public virtual ObjectResult<AplicacionesInfo> ListarAplicaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AplicacionesInfo>("ListarAplicaciones");
        }
    
        public virtual ObjectResult<EmpresaSwitchTransaccionesInfo> ListarEmpresaSwitchTransacciones(string iRazonSocial, string iSegmento)
        {
            var iRazonSocialParameter = iRazonSocial != null ?
                new ObjectParameter("iRazonSocial", iRazonSocial) :
                new ObjectParameter("iRazonSocial", typeof(string));
    
            var iSegmentoParameter = iSegmento != null ?
                new ObjectParameter("iSegmento", iSegmento) :
                new ObjectParameter("iSegmento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmpresaSwitchTransaccionesInfo>("ListarEmpresaSwitchTransacciones", iRazonSocialParameter, iSegmentoParameter);
        }
    
        public virtual ObjectResult<SecuencialCanalInfo> ConsultarSecuencialCanal(string iCanal)
        {
            var iCanalParameter = iCanal != null ?
                new ObjectParameter("iCanal", iCanal) :
                new ObjectParameter("iCanal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SecuencialCanalInfo>("ConsultarSecuencialCanal", iCanalParameter);
        }
    }
}
