//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtisCode.Aplicacion.Model.db_Local
{
    using System;
    
    public partial class SecuencialCanalInfo
    {
        public Nullable<long> SecuencialFacturas { get; set; }
        public Nullable<long> SecuencialNotaCredito { get; set; }
        public Nullable<long> SecuencialCotizaciones { get; set; }
    }
}
