//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtisCode.Aplicacion.Model.db_SafiParametros
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoElectronico
    {
        public int CodigoId { get; set; }
        public string ClaveAcceso { get; set; }
        public string DocumentoId { get; set; }
        public string EstadoRecepcion { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion { get; set; }
        public string NumeroAutorizacion { get; set; }
        public string Observaciones { get; set; }
        public string TipoDocumento { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<int> CodigoRelacionId { get; set; }
        public Nullable<int> CodigoRelacionIdReal { get; set; }
        public string PathCertificado { get; set; }
        public string Email { get; set; }
        public string BDD { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public Nullable<int> EstadoDocumentoId { get; set; }
        public Nullable<int> FirmadorElectronicoId { get; set; }
        public string DocumentoXml { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    }
}
