//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtisCode.Aplicacion.Model.db_SafiParametros
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SafiBDDParametrosEntities : DbContext
    {
        public SafiBDDParametrosEntities()
            : base("name=SafiBDDParametrosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComprobanteMasivo> ComprobanteMasivo { get; set; }
        public virtual DbSet<ComprobanteMasivoHistorial> ComprobanteMasivoHistorial { get; set; }
        public virtual DbSet<DocumentoElectronico> DocumentoElectronico { get; set; }
        public virtual DbSet<EstadoComprobanteMasivo> EstadoComprobanteMasivo { get; set; }
    }
}
