//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtisCode.Aplicacion.Model.db_Safi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CXCDIR
    {
        public int CodigoID { get; set; }
        public int Codigo { get; set; }
        public int CodRelacionID { get; set; }
        public string Clave { get; set; }
        public int Clave1 { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Actividad { get; set; }
        public System.DateTime Fecha { get; set; }
        public int TipoDoc { get; set; }
        public string Ruc { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> Pais { get; set; }
        public Nullable<int> Provincia { get; set; }
        public Nullable<int> Canton { get; set; }
        public Nullable<int> Parroquia { get; set; }
        public Nullable<int> Region { get; set; }
        public Nullable<int> Ciudad { get; set; }
        public Nullable<int> Zona { get; set; }
        public string Direc1 { get; set; }
        public string Direc2 { get; set; }
        public string Telef1 { get; set; }
        public string Telef2 { get; set; }
        public string Fax { get; set; }
        public string Grafico { get; set; }
        public string Referencia { get; set; }
        public string Repres { get; set; }
        public Nullable<decimal> RFuente { get; set; }
        public string Observa { get; set; }
        public string Uso { get; set; }
        public string Archivo { get; set; }
        public string Hoja { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> Limite { get; set; }
        public int Status { get; set; }
        public int Precio { get; set; }
        public int No_Div { get; set; }
        public string Iva { get; set; }
        public decimal Dcto { get; set; }
        public int Cme { get; set; }
        public decimal Total_Vtas { get; set; }
        public string Version { get; set; }
        public Nullable<int> Usuarios { get; set; }
        public Nullable<decimal> DB1 { get; set; }
        public Nullable<decimal> CR1 { get; set; }
        public Nullable<decimal> SL1 { get; set; }
        public Nullable<decimal> DB2 { get; set; }
        public Nullable<decimal> CR2 { get; set; }
        public Nullable<decimal> SL2 { get; set; }
        public Nullable<decimal> DB3 { get; set; }
        public Nullable<decimal> CR3 { get; set; }
        public Nullable<decimal> SL3 { get; set; }
        public Nullable<decimal> DB4 { get; set; }
        public Nullable<decimal> CR4 { get; set; }
        public Nullable<decimal> SL4 { get; set; }
        public Nullable<decimal> DB5 { get; set; }
        public Nullable<decimal> CR5 { get; set; }
        public Nullable<decimal> SL5 { get; set; }
        public Nullable<decimal> DB6 { get; set; }
        public Nullable<decimal> CR6 { get; set; }
        public Nullable<decimal> SL6 { get; set; }
        public Nullable<decimal> DB7 { get; set; }
        public Nullable<decimal> CR7 { get; set; }
        public Nullable<decimal> SL7 { get; set; }
        public Nullable<decimal> DB8 { get; set; }
        public Nullable<decimal> CR8 { get; set; }
        public Nullable<decimal> SL8 { get; set; }
        public Nullable<decimal> DB9 { get; set; }
        public Nullable<decimal> CR9 { get; set; }
        public Nullable<decimal> SL9 { get; set; }
        public Nullable<decimal> DB10 { get; set; }
        public Nullable<decimal> CR10 { get; set; }
        public Nullable<decimal> SL10 { get; set; }
        public Nullable<decimal> DB11 { get; set; }
        public Nullable<decimal> CR11 { get; set; }
        public Nullable<decimal> SL11 { get; set; }
        public Nullable<decimal> DB12 { get; set; }
        public Nullable<decimal> CR12 { get; set; }
        public Nullable<decimal> SL12 { get; set; }
        public string Estado { get; set; }
        public string EmailRepresentante { get; set; }
        public string Contador { get; set; }
        public string EmailContador { get; set; }
        public Nullable<int> TipoContribuyente { get; set; }
        public Nullable<int> IvaPresup { get; set; }
        public Nullable<int> CodRetRenta { get; set; }
        public Nullable<int> PrecioDis { get; set; }
        public Nullable<int> PrecioCre { get; set; }
        public Nullable<bool> Doc_Ele { get; set; }
        public string Dinardap { get; set; }
        public string Relacionado { get; set; }
        public Nullable<int> Clave2 { get; set; }
        public Nullable<int> TipoCta { get; set; }
        public string NumCta { get; set; }
        public string NomBco { get; set; }
        public string CodBco { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public string CodigoPostal { get; set; }
        public string TipoCliente { get; set; }
    }
}
