//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtisCode.Aplicacion.Model.db_Safi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CXPDIR
    {
        public int CodigoID { get; set; }
        public int Codigo { get; set; }
        public int CodRelacionID { get; set; }
        public string Clave { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Actividad { get; set; }
        public System.DateTime Fecha { get; set; }
        public int TipoDoc { get; set; }
        public string Ruc { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> Pais { get; set; }
        public Nullable<int> Provincia { get; set; }
        public Nullable<int> Canton { get; set; }
        public Nullable<int> Parroquia { get; set; }
        public Nullable<int> Region { get; set; }
        public Nullable<int> Ciudad { get; set; }
        public Nullable<int> Zona { get; set; }
        public string Direc1 { get; set; }
        public string Direc2 { get; set; }
        public string Telef1 { get; set; }
        public string Telef2 { get; set; }
        public string Fax { get; set; }
        public string Grafico { get; set; }
        public string Referencia { get; set; }
        public string Repres { get; set; }
        public Nullable<decimal> RFuente { get; set; }
        public string Observa { get; set; }
        public Nullable<int> TipoCta { get; set; }
        public string NumCta { get; set; }
        public string NomBco { get; set; }
        public string Uso { get; set; }
        public string Archivo { get; set; }
        public string Hoja { get; set; }
        public decimal Monto { get; set; }
        public Nullable<decimal> Limite { get; set; }
        public int No_Div { get; set; }
        public Nullable<decimal> Dcto { get; set; }
        public int Cme { get; set; }
        public decimal Total_Comp { get; set; }
        public Nullable<int> Imprenta { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> TipoContribuyente { get; set; }
        public Nullable<int> CtaGto { get; set; }
        public Nullable<int> CodRIr { get; set; }
        public Nullable<int> CodRIva { get; set; }
        public Nullable<int> CodRIva2 { get; set; }
        public Nullable<int> CtaIvaComp { get; set; }
        public Nullable<bool> Doc_Ele { get; set; }
        public string TipoProveedor { get; set; }
        public string Relacionado { get; set; }
        public string CodBanco { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public string CodigoPostal { get; set; }
    }
}
