//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtisCode.Aplicacion.Model.db_Safi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SafiEntities : DbContext
    {
        public SafiEntities()
            : base("name=SafiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FACHIS> FACHIS { get; set; }
        public virtual DbSet<CXCDIR> CXCDIR { get; set; }
        public virtual DbSet<tfacturas> tfacturas { get; set; }
        public virtual DbSet<tdocumentoscontador> tdocumentoscontador { get; set; }
        public virtual DbSet<CXPDIR> CXPDIR { get; set; }
    }
}
