//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtisCode.Aplicacion.Model.db_Safi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tdocumentoscontador
    {
        public long id { get; set; }
        public Nullable<long> nnum_doc { get; set; }
        public string tipo { get; set; }
        public string canal { get; set; }
    }
}
