//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtisCode.Aplicacion.Model.db_Safi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tdocumentoscontador
    {
        public long id { get; set; }
        public Nullable<long> nnum_doc { get; set; }
        public string tipo { get; set; }
        public string canal { get; set; }
    }
}
